# CAMLOPTLINK = "$(OCAMLFIND)" opt      -linkall get_ordinal.o

certicoq_plugin.cmxa: certicoq_plugin.cmx
	$(HIDE)$(TIMER) $(CAMLOPTLINK) get_ordinal.o $(CAMLDEBUG) $(CAMLFLAGS) $(FINDLIBPKGS) -a -o $@ $<
