COQ_SRC_SUBDIRS+=user-contrib/MetaCoq/Template
# OPENS=-open Metacoq_template_plugin
CAMLFLAGS+=$(OPENS)
CAMLFLAGS+=-w -33 # Unused opens
CAMLFLAGS+=-w -32 # Unused values
CAMLFLAGS+=-w -39 # Unused rec flagss
CAMLFLAGS+=-w -20 # Unused arguments
CAMLFLAGS+=-w -8 # Non-exhaustive matches produced by extraction

merlin-hook::
		$(HIDE)echo 'FLG $(OPENS)' >> .merlin