((coq-mode . ((coq-load-path . (
				(rec "../L1_QuotedCoq" "L1")
				(rec "../L1g" "L1g")
				(rec "../L2_typeStripped" "L2")
				(rec "../L2k_noCnstrParams" "L2k")
				(rec "../L2_5_box" "L2_5")
				(rec "../L3_flattenedApp" "L3")
				(rec "../L4_deBruijn" "L4")
                                (rec "../../libraries" "Libraries")
                                (rec "../L6_PCPS" "L6")
                                (rec "../common" "Common")
				(rec "../compcert" "compcert")
				(rec "../L7" "L7")
				(rec "../../benchmarks/" "Benchmarks")
				(rec "../Runtime/" "runtime")
                                )))))
