((coq-mode . (coq-load-path . (("../compcert" "compcert")
                               ("../../libraries" "Libraries")
                               ("../common" "Common")
                               ("../L1_QuotedCoq" "L1")
                               ("../L1g" "L1g")
                               ("../L1_QuotedCoq" "L1")
                               ("../L2_typeStripped" "L2")
                               ("../LambdaBoxMut" "LambdaBoxMut")
                               ("../L2_5_box" "L2_5")
                               ("../LambdaBoxMut_flattenedApp" "LambdaBoxMut")
                               ("../LambdaBoxLocal" "LambdaBoxLocal")
                               ("." "LambdaANF")
                               ("../Codegen" "Codegen")))))
