((coq-mode . (coq-load-path . (("../compcert" "compcert")
                               ("../../libraries" "Libraries")
                               ("../common" "Common")
                               ("../L1_QuotedCoq" "L1")
                               ("../L1g" "L1g")
                               ("../L1_QuotedCoq" "L1")
                               ("../L2_typeStripped" "L2")
                               ("../L2k_noCnstrParams" "L2k")
                               ("../L2_5_box" "L2_5")
                               ("../L3_flattenedApp" "L3")
                               ("../L4_deBruijn" "L4")
                               ("." "L6")
                               ("../L7" "L7")))))
